server:
  port: 7002

eureka:
  instance:
  #    hostname: localhost
  #  集群
  hostname: eureka7002.com
  client:
    #自己注册自己
    register-with-eureka: true
    #自己就是注册中心，集群设置为true，配合使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/